import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Заказы",
  description: "Generated by create next app",
};

export default function Orders() {
  return <div>Заказы</div>;
}
