import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Корзина",
  description: "Generated by create next app",
};

export default function Basket() {
  return <div>Корзина</div>;
}
