import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Layout } from "antd";
import { Content } from "antd/es/layout/layout";
import { AppHeader } from "./_components/app-header";
import AppProviders from "./_app-providers";

import "./globals.css";

const inter = Inter({
  variable: "--Inter",
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "Portal Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <AppProviders>
            <Layout>
              <AppHeader />
              <Content>{children}</Content>
            </Layout>
          </AppProviders>
        </div>
      </body>
    </html>
  );
}
