import { Suspense } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppHeader } from "./_components/app-header";
import AppProviders from "./_app-providers";

import "./globals.css";
import { Loader } from "@/ui/loader";

const inter = Inter({
  variable: "--Inter",
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "e.way",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProviders>
          <div className="flex flex-col items-center gap-2">
            <AppHeader />
            <Suspense fallback={<Loader />}>
              <div className="max-w-screen-xl w-full grow">{children}</div>
            </Suspense>
          </div>
        </AppProviders>
      </body>
    </html>
  );
}
