import { Metadata } from "next";
import { useServerTranslation } from "@/i18n";
import { fetchCatalog } from "../api/catalog/route";
import { Banner } from "./_components/banner";
import { CatalogTable } from "./_components/catalog-table";
import { CategoryTree } from "./_components/category-tree";
import { FeaturedFilters } from "./_components/featured-filters";
import { Producers } from "./_components/producers";
import { SearchInfo } from "./_components/search-info";
import { Shortcuts } from "./_components/shortcuts";

export const metadata: Metadata = {
  title: "Каталог",
  description: "Generated by create next app",
};

async function getData(search?: string | null) {
  return fetchCatalog({ search });
}

interface IProps {
  searchParams?: {
    search?: string;
  };
}

export default async function Catalog({ searchParams }: IProps) {
  const { t } = await useServerTranslation("catalog");
  const { items, count, categories } = await getData(searchParams?.search);

  return (
    <div className="flex flex-col gap-4 px-2">
      <Shortcuts t={t} />
      <div className="flex gap-6">
        <div className="flex flex-col gap-4 shrink-0 grow-0 w-60">
          <CategoryTree items={categories} />
          <FeaturedFilters />
          <Producers />
        </div>
        <div className="flex flex-col gap-2 grow shrink w-0">
          <Banner />
          <SearchInfo text={searchParams?.search} count={count} />
          <CatalogTable data={items} t={t} />
        </div>
      </div>
    </div>
  );
}
