import { mockItems } from "@/mock-data/items";
import { Metadata } from "next";
import { CatalogTable } from "./_components/catalog-table";
import { Shortcuts } from "./_components/shortcuts";
import { CategoryTree } from "./_components/category-tree";
import Image from "next/image";
import { fetchCatalog } from "@/api";
import { FeaturedFilters } from "./_components/faetured-filters";
import { Suspense } from "react";
import { SearchInfo } from "./_components/search-info";

export const metadata: Metadata = {
  title: "Каталог",
  description: "Generated by create next app",
};

async function getData(search?: string | null) {
  return fetchCatalog({ search });
}

interface IProps {
  searchParams?: {
    search?: string;
  };
}

export default async function Catalog({ searchParams }: IProps) {
  const { items, count, categories } = await getData(searchParams?.search);

  return (
    <div className="flex flex-col gap-4 px-2">
      <Shortcuts />
      <div className="flex gap-6">
        <div className="flex flex-col gap-2">
          <CategoryTree items={categories} />
          <FeaturedFilters />
        </div>
        <div className="flex flex-col gap-2">
          <Image
            alt="banner"
            src="/2000_315_eway_v_katalog.png"
            width={1100}
            height={157}
            priority={false}
          />
          <SearchInfo text={searchParams?.search} count={count} />
          <CatalogTable data={items} />
        </div>
      </div>
    </div>
  );
}
